// ✅ Error/Success codes cho Quản lý Đơn
export const APPLICATION_NOT_FOUND_CODE = 'APPLICATION_NOT_FOUND';
export const EMAIL_OR_STUDENT_ID_EXISTS_CODE = 'EMAIL_OR_STUDENT_ID_EXISTS';
export const APPLICATION_ALREADY_PROCESSED_CODE =
  'APPLICATION_ALREADY_PROCESSED';
export const APPROVAL_FAILED_CODE = 'APPROVAL_FAILED';
