// ✅ Error/Success codes (giữ ngắn gọn, rõ nghĩa)
export const VALIDATION_ERROR = 'VALIDATION_ERROR';
export const EMAIL_EXISTS_CODE = 'EMAIL_EXISTS';
export const REGISTRATION_FAILED_CODE = 'REGISTRATION_FAILED';
export const INVALID_CREDENTIALS_CODE = 'INVALID_CREDENTIALS';
export const ACCOUNT_BLOCKED_CODE = 'ACCOUNT_BLOCKED';
export const SERVER_ERROR_CODE = 'SERVER_ERROR';
export const NO_REFRESH_TOKEN_CODE = 'NO_REFRESH_TOKEN';
export const REFRESH_TOKEN_EXPIRED_CODE = 'REFRESH_TOKEN_EXPIRED';
export const SESSION_NOT_FOUND_CODE = 'SESSION_NOT_FOUND';
export const INVALID_REFRESH_TOKEN_CODE = 'INVALID_REFRESH_TOKEN';
export const USER_NOT_FOUND_CODE = 'USER_NOT_FOUND';
export const INVALID_USER_CODE = 'INVALID_USER';
export const LOGOUT_FAILED_CODE = 'LOGOUT_FAILED';

// OTP codes
export const OTP_SENT = 'OTP_SENT';
export const OTP_VERIFY_SUCCESS_CODE = 'OTP_VERIFY_SUCCESS';
export const OTP_INVALID_CODE = 'OTP_INVALID';
export const OTP_EXPIRED_CODE = 'OTP_EXPIRED';
export const OTP_ATTEMPTS_EXCEEDED_CODE = 'OTP_ATTEMPTS_EXCEEDED';
export const OTP_NOT_FOUND_CODE = 'OTP_NOT_FOUND';
