// ✅ Error codes
export const VALIDATION_ERROR = 'VALIDATION_ERROR';
export const EMAIL_EXISTS = 'EMAIL_EXISTS';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';
export const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
export const ACCOUNT_BLOCKED = 'ACCOUNT_BLOCKED';
export const SERVER_ERROR = 'SERVER_ERROR';
export const NO_REFRESH_TOKEN = 'NO_REFRESH_TOKEN';
export const REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED';
export const SESSION_NOT_FOUND = 'SESSION_NOT_FOUND';
export const INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const INVALID_USER = 'INVALID_USER';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';
