// ✅ Category codes (Error / Success)
export const CATEGORY_CREATE_SUCCESS_CODE = 'CATEGORY_CREATE_SUCCESS';
export const CATEGORY_UPDATE_SUCCESS_CODE = 'CATEGORY_UPDATE_SUCCESS';
export const CATEGORY_DELETE_SUCCESS_CODE = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_GET_SUCCESS_CODE = 'CATEGORY_GET_SUCCESS';
export const CATEGORY_GET_DETAIL_SUCCESS_CODE = 'CATEGORY_GET_DETAIL_SUCCESS';

export const CATEGORY_EXISTS_CODE = 'CATEGORY_EXISTS';
export const CATEGORY_NOT_FOUND_CODE = 'CATEGORY_NOT_FOUND';
export const CATEGORY_CREATE_FAILED_CODE = 'CATEGORY_CREATE_FAILED';
export const CATEGORY_UPDATE_FAILED_CODE = 'CATEGORY_UPDATE_FAILED';
export const CATEGORY_DELETE_FAILED_CODE = 'CATEGORY_DELETE_FAILED';
export const CATEGORY_INVALID_ID_CODE = 'CATEGORY_INVALID_ID';
export const CATEGORY_PARENT_NOT_FOUND_CODE = 'CATEGORY_PARENT_NOT_FOUND';
export const CATEGORY_STATUS_INVALID_CODE = 'CATEGORY_STATUS_INVALID';
