// ✅ Comment codes (Error / Success)
export const COMMENT_CREATE_SUCCESS_CODE = 'COMMENT_CREATE_SUCCESS';
export const COMMENT_UPDATE_SUCCESS_CODE = 'COMMENT_UPDATE_SUCCESS';
export const COMMENT_DELETE_SUCCESS_CODE = 'COMMENT_DELETE_SUCCESS';
export const COMMENT_GET_SUCCESS_CODE = 'COMMENT_GET_SUCCESS';
export const COMMENT_GET_DETAIL_SUCCESS_CODE = 'COMMENT_GET_DETAIL_SUCCESS';

export const COMMENT_EXISTS_CODE = 'COMMENT_EXISTS';
export const COMMENT_NOT_FOUND_CODE = 'COMMENT_NOT_FOUND';
export const COMMENT_CREATE_FAILED_CODE = 'COMMENT_CREATE_FAILED';
export const COMMENT_UPDATE_FAILED_CODE = 'COMMENT_UPDATE_FAILED';
export const COMMENT_DELETE_FAILED_CODE = 'COMMENT_DELETE_FAILED';
export const COMMENT_INVALID_ID_CODE = 'COMMENT_INVALID_ID';
