// common/message/document.code.js

// ✅ Document codes (Error / Success)
export const DOCUMENT_CREATE_SUCCESS_CODE = 'DOCUMENT_CREATE_SUCCESS';
export const DOCUMENT_UPDATE_SUCCESS_CODE = 'DOCUMENT_UPDATE_SUCCESS';
export const DOCUMENT_DELETE_SUCCESS_CODE = 'DOCUMENT_DELETE_SUCCESS';
export const DOCUMENT_GET_SUCCESS_CODE = 'DOCUMENT_GET_SUCCESS';
export const DOCUMENT_ASSIGN_USERS_SUCCESS_CODE =
  'DOCUMENT_ASSIGN_USERS_SUCCESS';
export const DOCUMENT_REMOVE_USER_SUCCESS_CODE = 'DOCUMENT_REMOVE_USER_SUCCESS';

export const DOCUMENT_EXISTS_CODE = 'DOCUMENT_EXISTS';
export const DOCUMENT_NOT_FOUND_CODE = 'DOCUMENT_NOT_FOUND';
export const DOCUMENT_CREATE_FAILED_CODE = 'DOCUMENT_CREATE_FAILED';
export const DOCUMENT_UPDATE_FAILED_CODE = 'DOCUMENT_UPDATE_FAILED';
export const DOCUMENT_DELETE_FAILED_CODE = 'DOCUMENT_DELETE_FAILED';
export const DOCUMENT_ASSIGNMENT_FAILED_CODE =
  'DOCUMENT_ASSIGNMENT_FAILED_CODE';
export const DOCUMENT_REMOVAL_FAILED_CODE = 'DOCUMENT_REMOVAL_FAILED_CODE';
