// ✅ Document Category codes (Error / Success)
export const DOC_CATEGORY_CREATE_SUCCESS_CODE = 'DOC_CATEGORY_CREATE_SUCCESS';
export const DOC_CATEGORY_UPDATE_SUCCESS_CODE = 'DOC_CATEGORY_UPDATE_SUCCESS';
export const DOC_CATEGORY_DELETE_SUCCESS_CODE = 'DOC_CATEGORY_DELETE_SUCCESS';

export const DOC_CATEGORY_EXISTS_CODE = 'DOC_CATEGORY_EXISTS';
export const DOC_CATEGORY_NOT_FOUND_CODE = 'DOC_CATEGORY_NOT_FOUND';
export const DOC_CATEGORY_INVALID_ID_CODE = 'DOC_CATEGORY_INVALID_ID';
export const DOC_CATEGORY_PARENT_NOT_FOUND_CODE =
  'DOC_CATEGORY_PARENT_NOT_FOUND';
