// common/message/event.code.js

export const EVENT_NOT_FOUND_CODE = 'EVENT_NOT_FOUND';
export const EVENT_SLUG_EXISTS_CODE = 'EVENT_SLUG_EXISTS';
export const EVENT_IS_FULL_CODE = 'EVENT_IS_FULL';
export const REGISTRATION_DEADLINE_PASSED_CODE = 'REGISTRATION_DEADLINE_PASSED';
export const USER_ALREADY_REGISTERED_CODE = 'USER_ALREADY_REGISTERED';
export const REGISTRATION_NOT_FOUND_CODE = 'REGISTRATION_NOT_FOUND';
export const ALREADY_CHECKED_IN_CODE = 'ALREADY_CHECKED_IN';
