// ✅ Question Codes
export const QUESTION_CREATE_SUCCESS_CODE = 'QUESTION_CREATE_SUCCESS';
export const QUESTION_UPDATE_SUCCESS_CODE = 'QUESTION_UPDATE_SUCCESS';
export const QUESTION_DELETE_SUCCESS_CODE = 'QUESTION_DELETE_SUCCESS';
export const QUESTION_GET_SUCCESS_CODE = 'QUESTION_GET_SUCCESS';
export const QUESTION_NOT_FOUND_CODE = 'QUESTION_NOT_FOUND';

// ✅ Answer Codes
export const ANSWER_CREATE_SUCCESS_CODE = 'ANSWER_CREATE_SUCCESS';
export const ANSWER_UPDATE_SUCCESS_CODE = 'ANSWER_UPDATE_SUCCESS';
export const ANSWER_DELETE_SUCCESS_CODE = 'ANSWER_DELETE_SUCCESS';
export const ANSWER_GET_SUCCESS_CODE = 'ANSWER_GET_SUCCESS';
export const ANSWER_VOTE_SUCCESS_CODE = 'ANSWER_VOTE_SUCCESS';
export const ANSWER_NOT_FOUND_CODE = 'ANSWER_NOT_FOUND';
export const ANSWER_INVALID_VOTE_TYPE_CODE = 'ANSWER_INVALID_VOTE_TYPE';
