// ✅ Tag codes (Error / Success)
export const TAG_CREATE_SUCCESS_CODE = 'TAG_CREATE_SUCCESS';
export const TAG_UPDATE_SUCCESS_CODE = 'TAG_UPDATE_SUCCESS';
export const TAG_DELETE_SUCCESS_CODE = 'TAG_DELETE_SUCCESS';
export const TAG_GET_SUCCESS_CODE = 'TAG_GET_SUCCESS';
export const TAG_GET_DETAIL_SUCCESS_CODE = 'TAG_GET_DETAIL_SUCCESS';

export const TAG_EXISTS_CODE = 'TAG_EXISTS';
export const TAG_NOT_FOUND_CODE = 'TAG_NOT_FOUND';
export const TAG_CREATE_FAILED_CODE = 'TAG_CREATE_FAILED';
export const TAG_UPDATE_FAILED_CODE = 'TAG_UPDATE_FAILED';
export const TAG_DELETE_FAILED_CODE = 'TAG_DELETE_FAILED';
export const TAG_INVALID_ID_CODE = 'TAG_INVALID_ID';
