// ✅ Transaction codes (Error / Success)
export const TRANSACTION_CREATE_SUCCESS_CODE = 'TRANSACTION_CREATE_SUCCESS';
export const TRANSACTION_UPDATE_SUCCESS_CODE = 'TRANSACTION_UPDATE_SUCCESS';
export const TRANSACTION_DELETE_SUCCESS_CODE = 'TRANSACTION_DELETE_SUCCESS';
export const TRANSACTION_GET_SUCCESS_CODE = 'TRANSACTION_GET_SUCCESS';
export const TRANSACTION_GET_DETAIL_SUCCESS_CODE =
  'TRANSACTION_GET_DETAIL_SUCCESS';

export const TRANSACTION_EXISTS_CODE = 'TRANSACTION_EXISTS';
export const TRANSACTION_NOT_FOUND_CODE = 'TRANSACTION_NOT_FOUND';
export const TRANSACTION_CREATE_FAILED_CODE = 'TRANSACTION_CREATE_FAILED';
export const TRANSACTION_UPDATE_FAILED_CODE = 'TRANSACTION_UPDATE_FAILED';
export const TRANSACTION_DELETE_FAILED_CODE = 'TRANSACTION_DELETE_FAILED';
export const TRANSACTION_INVALID_ID_CODE = 'TRANSACTION_INVALID_ID';
