// Validation
export const VALIDATION_ERROR = 'VALIDATION_ERROR';
export const INVALID_ID_CODE = 'INVALID_ID';
export const INVALID_NAME_CODE = 'INVALID_NAME';
export const INVALID_EMAIL_CODE = 'INVALID_EMAIL';
export const INVALID_PHONE_CODE = 'INVALID_PHONE';

// CRUD
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';

// Errors
export const USER_NOT_FOUND_CODE = 'USER_NOT_FOUND';
export const NO_UPDATE_CODE = 'NO_UPDATE';
export const EMAIL_EXISTS_CODE = 'EMAIL_EXISTS';
export const PHONE_EXISTS_CODE = 'PHONE_EXISTS';
export const USER_CREATE_FAILED_CODE = 'USER_CREATE_FAILED';
export const USER_UPDATE_FAILED_CODE = 'USER_UPDATE_FAILED';
export const USER_DELETE_FAILED_CODE = 'USER_DELETE_FAILED';

// Profile
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS';
export const PROFILE_NOT_FOUND_CODE = 'PROFILE_NOT_FOUND';

// Role & Permission
export const ROLE_NOT_FOUND_CODE = 'ROLE_NOT_FOUND';
export const PERMISSION_DENIED_CODE = 'PERMISSION_DENIED';
