// ========================== VALIDATION ==========================
export const VALIDATION_ERROR = 'VALIDATION_ERROR';
export const INVALID_ID_CODE = 'INVALID_ID';
export const INVALID_NAME_CODE = 'INVALID_NAME';
export const INVALID_EMAIL_CODE = 'INVALID_EMAIL';
export const INVALID_PHONE_CODE = 'INVALID_PHONE';
export const INVALID_ROLE_ID_CODE = 'INVALID_ROLE_ID';
export const KEYWORD_REQUIRED_CODE = 'KEYWORD_REQUIRED';
export const INVALID_PASSWORD_CODE = 'INVALID_PASSWORD';

// ========================== USER - CRUD ==========================
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_HARD_DELETE_SUCCESS = 'USER_HARD_DELETE_SUCCESS';
export const USER_RESTORE_SUCCESS = 'USER_RESTORE_SUCCESS';

// ========================== USER - ERRORS ==========================
export const USER_NOT_FOUND_CODE = 'USER_NOT_FOUND';
export const USER_NOT_FOUND_DELETED_CODE = 'USER_NOT_FOUND_DELETED';
export const NO_DELETED_USERS_CODE = 'NO_DELETED_USERS';
export const NO_UPDATE_CODE = 'NO_UPDATE';
export const EMAIL_EXISTS_CODE = 'EMAIL_EXISTS';
export const PHONE_EXISTS_CODE = 'PHONE_EXISTS';
export const USER_CREATE_FAILED_CODE = 'USER_CREATE_FAILED';
export const USER_UPDATE_FAILED_CODE = 'USER_UPDATE_FAILED';
export const USER_DELETE_FAILED_CODE = 'USER_DELETE_FAILED';
export const UPDATE_FAILURE_CODE = 'UPDATE_FAILURE';

// ========================== USER - STATUS ==========================
export const USER_ACTIVATE_SUCCESS = 'USER_ACTIVATE_SUCCESS';
export const USER_DEACTIVATE_SUCCESS = 'USER_DEACTIVATE_SUCCESS';
export const USER_TOGGLE_ACTIVE_FAILED_CODE = 'USER_TOGGLE_ACTIVE_FAILED';

// ========================== USER - EMAIL VERIFICATION ==========================
export const EMAIL_VERIFY_SUCCESS = 'EMAIL_VERIFY_SUCCESS';
export const EMAIL_ALREADY_VERIFIED_CODE = 'EMAIL_ALREADY_VERIFIED';
export const VERIFY_FAILURE_CODE = 'VERIFY_FAILURE';

// ========================== USER - SEARCH & FILTER ==========================
export const USER_SEARCH_SUCCESS = 'USER_SEARCH_SUCCESS';
export const SEARCH_NO_RESULT_CODE = 'SEARCH_NO_RESULT';
export const USER_FETCH_BY_ROLE_SUCCESS = 'USER_FETCH_BY_ROLE_SUCCESS';
export const NO_USERS_IN_ROLE_CODE = 'NO_USERS_IN_ROLE';
export const USER_FETCH_DELETED_SUCCESS = 'USER_FETCH_DELETED_SUCCESS';

// ========================== USER - STATISTICS ==========================
export const USER_STATS_SUCCESS = 'USER_STATS_SUCCESS';
export const STATS_FAILURE_CODE = 'STATS_FAILURE';

// ========================== PROFILE ==========================
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_NOT_FOUND_CODE = 'PROFILE_NOT_FOUND';
export const PROFILE_UPDATE_FAILED_CODE = 'PROFILE_UPDATE_FAILED';

// ========================== AUTHENTICATION ==========================
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED_CODE = 'LOGIN_FAILED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED_CODE = 'LOGOUT_FAILED';
export const TOKEN_INVALID_CODE = 'TOKEN_INVALID';
export const TOKEN_EXPIRED_CODE = 'TOKEN_EXPIRED';
export const UNAUTHORIZED_CODE = 'UNAUTHORIZED';

// ========================== PASSWORD ==========================
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAILED_CODE = 'PASSWORD_RESET_FAILED';
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS';
export const PASSWORD_CHANGE_FAILED_CODE = 'PASSWORD_CHANGE_FAILED';
export const PASSWORD_MISMATCH_CODE = 'PASSWORD_MISMATCH';
export const OLD_PASSWORD_INCORRECT_CODE = 'OLD_PASSWORD_INCORRECT';

// ========================== ROLE ==========================
export const ROLE_FETCH_SUCCESS = 'ROLE_FETCH_SUCCESS';
export const ROLE_CREATE_SUCCESS = 'ROLE_CREATE_SUCCESS';
export const ROLE_UPDATE_SUCCESS = 'ROLE_UPDATE_SUCCESS';
export const ROLE_DELETE_SUCCESS = 'ROLE_DELETE_SUCCESS';
export const ROLE_ASSIGN_SUCCESS = 'ROLE_ASSIGN_SUCCESS';

export const ROLE_NOT_FOUND_CODE = 'ROLE_NOT_FOUND';
export const ROLE_NAME_EXISTS_CODE = 'ROLE_NAME_EXISTS';
export const ROLE_IN_USE_CODE = 'ROLE_IN_USE';
export const ROLE_CREATE_FAILED_CODE = 'ROLE_CREATE_FAILED';
export const ROLE_UPDATE_FAILED_CODE = 'ROLE_UPDATE_FAILED';
export const ROLE_DELETE_FAILED_CODE = 'ROLE_DELETE_FAILED';
export const ROLE_ASSIGN_FAILED_CODE = 'ROLE_ASSIGN_FAILED';

// ========================== PERMISSION ==========================
export const PERMISSION_FETCH_SUCCESS = 'PERMISSION_FETCH_SUCCESS';
export const PERMISSION_CREATE_SUCCESS = 'PERMISSION_CREATE_SUCCESS';
export const PERMISSION_UPDATE_SUCCESS = 'PERMISSION_UPDATE_SUCCESS';
export const PERMISSION_DELETE_SUCCESS = 'PERMISSION_DELETE_SUCCESS';
export const PERMISSION_GRANT_SUCCESS = 'PERMISSION_GRANT_SUCCESS';
export const PERMISSION_REVOKE_SUCCESS = 'PERMISSION_REVOKE_SUCCESS';

export const PERMISSION_NOT_FOUND_CODE = 'PERMISSION_NOT_FOUND';
export const PERMISSION_DENIED_CODE = 'PERMISSION_DENIED';
export const PERMISSION_NAME_EXISTS_CODE = 'PERMISSION_NAME_EXISTS';
export const PERMISSION_IN_USE_CODE = 'PERMISSION_IN_USE';
export const PERMISSION_CREATE_FAILED_CODE = 'PERMISSION_CREATE_FAILED';
export const PERMISSION_UPDATE_FAILED_CODE = 'PERMISSION_UPDATE_FAILED';
export const PERMISSION_DELETE_FAILED_CODE = 'PERMISSION_DELETE_FAILED';
export const PERMISSION_GRANT_FAILED_CODE = 'PERMISSION_GRANT_FAILED';
export const PERMISSION_REVOKE_FAILED_CODE = 'PERMISSION_REVOKE_FAILED';

// ========================== GENERAL ==========================
export const FORBIDDEN_CODE = 'FORBIDDEN';
export const INTERNAL_SERVER_ERROR_CODE = 'INTERNAL_SERVER_ERROR';
export const BAD_REQUEST_CODE = 'BAD_REQUEST';
export const NOT_FOUND_CODE = 'NOT_FOUND';
export const CONFLICT_CODE = 'CONFLICT';
